todoapp/urls.py
from django.urls import path
from . import views
app_name = 'todoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('todo/', views.todoappView, name='todo'),
    path('addTodoItem/',views.addTodoView), 
    path('deleteTodoItem/<int:id>/', views.deleteTodoView), 
    path('updateTodoItem/<int:id>/', views.updateTodoView),
] 

todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls',)),
]

todoapp/models.py
from django.db import models


# Create your models here.
class TodoListItem(models.Model):
    content = models.TextField() 

todoapp/views.py
from django.shortcuts import render
from .models import TodoListItem 
from django.http import HttpResponseRedirect 
# Create your views here.
def index(request):
    return render(request, 'index.html')



def todoappView(request):
    all_todo_items = TodoListItem.objects.all()
    return render(request, 'todolist.html',  {'all_items':all_todo_items})


def addTodoView(request):
    new_item = TodoListItem()
    new_item.content = request.POST.get('content')
    new_item.save()
    return HttpResponseRedirect('/todo/') 


def deleteTodoView(request, id):
    y = TodoListItem.objects.get(id= id)
    y.delete()
    return HttpResponseRedirect('/todo/') 

def updateTodoView(request,id):
    
    updated_content = request.POST.get('updated_content')
    print(f"{updated_content}")
    if updated_content!='':
        TodoListItem.objects.filter(pk=id).update(content=updated_content)
 
    return HttpResponseRedirect('/todo/') 

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Google Fonts - Courier Prime -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <style>
        /* Custom styles */
        body {
            font-family: 'Courier Prime', monospace; /* Apply Courier Prime font to the entire body */
            background-color: #F9F9E0; /* Set background color */
        }
        .container {
            background-color: #F9F9E0; /* Set background color */
            margin-top: 200px;
        }
        .card-header {
            font-family: 'Courier Prime', monospace; /* Apply Courier Prime font to the card header */
            background-color: #fbaacb;
        }
        .card-footer {
            font-family: 'Courier Prime', monospace; /* Apply Courier Prime font to the card footer */
            background-color: #fbaacb;
            padding-top: 10px;
        }
            
    </style>
    <title>To Do App</title>
</head>
<body>
    <div class="container">
        <div class="card text-center">
            <div class="card-header">
                <h2 style="margin-top: 5px; font-weight: bold;">Hello!</h2>
            </div>
            <div class="card-body" style="background-color: #bdd6da;">
                <h4 class="card-title">Welcome to the app</h4>
                
                <p class="card-text" >Make life easier by creating ToDo List</p>
                <a href="{% url 'todoapp:todo' %}" class="btn btn-primary" style="font-size: 1.1em;">Start Now!</a>
            </div>
            <div class="card-footer ">
                <h5>By Michelle Miranda - 22112023</h5>
            </div>
        </div>
    </div>
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>

templates/todolist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Google Fonts - Courier Prime -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <style>
        /* Global style for center alignment */
        body, .container {
            font-family: 'Courier Prime', monospace;
            text-align: center;
        
        }
       
    </style>
    <title>Todo List</title>
</head>
<body style="background-color: #D2E9E9;">
    <div class="container">
        <div class="row" style="margin-top: 20px">
            <div class="col">
                <div class="row">
                    <form class="form-inline" action="/addTodoItem/" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-8">
                                <div class="form-group mb-2" >
                                    <label for="content" class="sr-only"></label>
                                    <input type="text" class="form-control" name="content" placeholder="Research" style="width: 83%;">
                                </div>
                            </div>
                            <div class="col-4" style="margin-top: 25px">
                                <button type="submit" class="btn btn-primary mb-2" style="width: 40vh;">Add Todo</button>
                            </div>
                        </div>
                    </form>
                </div>
                {% for i in all_items %}
                <div class="row" style="margin-top: 20px;">
                    <div class="col-6" style="width: 36%;">
                        <div class="card text-white bg-light mb-3">
                            <div class="card-body" style="color: black;">{{ i.content }}</div>
                        </div>
                    </div>
                    <div class="col-2" style="width: 10%;">
                        <!-- Delete Form -->
                        <form action="/deleteTodoItem/{{ i.id }}/" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary" style="margin-top: 10px; background-color: rgba(207, 2, 2, 0.862);">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </button>
                        </form>
                    </div>
                    <div class="col-3" style="width: 10%;">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin-top: 10px; background-color: green; ">
                            Update
                        </button>
                        <!-- Update Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Update Task</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <form action="/updateTodoItem/{{ i.id }}/" method="post">
                                        {% csrf_token %}
                                        <div class="modal-body">
                                            <input type="text" class="form-control" name="updated_content" placeholder="Enter updated Task" value="{{ i.content }}">
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>